### ISSUE TITLE
[Feature Request] Play track mix after playing track from search results

### ISSUE THREAD

**Issue by Emrykh** [DJDoubleD/refreezer#18]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**

hello. Thanks for all you do. I just have a request. Can you add automatic song mix to a song I seach and play(lokee a song radio)? Most times, after playing a searched song, the next suggested song in the search tab starts to play. The lyrics too, please 🥹

**Comment by Emrykh** [comment]
hello. Thanks for all you do. I just have a request. Can you add automatic song mix to a song I seach and play(lokee a song radio)? Most times, after playing a searched song, the next suggested song in the search tab starts to play. The lyrics too, please 🥹

**Comment by DJDoubleD** [comment]
I am sorry, I'm not sure I understand your question.
I guess you are asking to change the behavior of the queue loaded when playing a song from search results.
If this is correct, I'm afraid I won't be changing this as this is an inherent feature of the app.
When you play a song from search results, you'll notice that the queue source is explicitly stated as "search" ("playing from: search" in horizontal screen mode).
So this is by design.

If you want to play a generated list of tracks based on your searched track, you can just long press the track in the search results and select the "Play Mix" option.
(I will check if I can change it's current behavior so that the 1st track of the mix is actually the selected track the mix is based on)

In case I misunderstood your request, please clarify...
I also do not understand the lyrics question, when the lyrics are available on Deezer, they are already available in the app.
If you found examples where lyrics are available in the Deezer web player/app and not in ReFreezer, please provide examples.
