### ISSUE TITLE
[Bug] Android auto

### ISSUE THREAD

**Issue by Micka0123456** [DJDoubleD/refreezer#36]
# **🐞 Bug Report**

## **Describe the bug**

Bonjour, 
Impossible de faire fonctionner l'application sur Android auto.
Je vois bien l'application mais impossible de l'utiliser. Je clique dessus l'application se lance mais rien ne s'affiche à l'écran.
Je ne peux pas lancer de musique et faire des recherches.

**Comment by DJDoubleD** [comment]
Please use English to report and discuss issues (there are plenty of free, high quality translation tools out there).

I'm assuming you are trying to launch ReFreezer from your car's head unit directly.
Because of some limitations in the resent android (auto) versions, this currently does not work as the Android auto head unit isn't able to start the background streaming service that ReFreezer uses to playback tracks.

Next time you start your car, please try to open the ReFreezer app on your phone **_before_** opening the app on your car's Android Auto head unit.
This should normally work, as this is how I am able to [test the app on the Android Auto Desktop Head Unit emulator](https://github.com/DJDoubleD/refreezer/wiki/Set%E2%80%90up-Full-Virtual-Android-Auto-Head-Unit-Debugging).

**Comment by Micka0123456** [comment]
Thank you. For your return everything works correctly by launching the application before android auto.

**Comment by Bwangster12** [comment]
> Please use English to report and discuss issues (there are plenty of free, high quality translation tools out there).
> 
> I'm assuming you are trying to launch ReFreezer from your car's head unit directly. Because of some limitations in the resent android (auto) versions, this currently does not work as the Android auto head unit isn't able to start the background streaming service that ReFreezer uses to playback tracks.
> 
> Next time you start your car, please try to open the ReFreezer app on your phone **_before_** opening the app on your car's Android Auto head unit. This should normally work, as this is how I am able to [test the app on the Android Auto Desktop Head Unit emulator](https://github.com/DJDoubleD/refreezer/wiki/Set%E2%80%90up-Full-Virtual-Android-Auto-Head-Unit-Debugging).

I wonder if its possible to use something like MacroDroid or Tasker to start that background Refreezer process when Android Auto starts.  What is the name of the process?

**Comment by brian52591** [comment]
Is there a way to use voice controls with Refreezer? (Android Auto)
