### ISSUE TITLE
[Bug]  Spotify Importer not working 

### ISSUE THREAD

**Issue by cyriotic3** [DJDoubleD/refreezer#6]
# **🐞 Bug Report**

## **Describe the bug**

Spotify Importer not working 

---

### **Is this a regression?**

this is my first time with this app, so idk if this is present on the older versions 
---

### **To Reproduce**

1. Library, Import, Spotify v2
2. do all of the thing says there
3. after pressing Agree on Spotify's "Allow Spotify to connect to:" page, the bug should occur 

---

### **Expected behaviour**

for Spotify to authorize

---

### **Screenshots**

https://github.com/user-attachments/assets/61bbfe06-d594-43e5-943b-59fb7d5334dd

---

### **Additional context**

none

**Comment by DJDoubleD** [comment]
Your video doesn't end on an error, it just shows the embedded browser waiting for the response from the Spotify server...
You might need to give it a bit more time to respond or try again while being connected to a different network (no VPN, mobile data instead of wifi, ...).

Please also make sure you enter the correct redirect url when creating the app credentials for Spotify (`http://localhost:42069` like indicated in the instructions), as the app listens for the authorization code from Spotify on that address.

I'm afraid I'm unable to reproduce the problem (tested on multiple devices)

**Comment by spftware** [comment]
I also experienced this with Firefox. You just copy the URL in the mail  browser you're using and it works fine.

**Comment by cyriotic3** [comment]
I've got it working now, it was in fact the internet i was using, switching to a different one works
